name: Deploy to Github Pages
on:
  push:
    branches:
      - angular-14
jobs:
  Build-HTML:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build.yml
    with:
        ng-base-href: '/sam-design-system-site/'
  Deploy-HTML:
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    needs: Build-HTML
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download HTML Assets
        # If closing PR, build will not occur so nothing to download
        if: github.event.action != 'closed'
        uses: actions/download-artifact@v4
        with:
          name: html-assets
          path: ./docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs
          clean-exclude: pr-preview/
          force: false
