name: Deploy to Github Pages
on:
  push:
    branches:
      - angular-14
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Node Packages
        run: npm i
      - name: Build Angular HTMLs
        run: npm run build --output-path docs
      # - name: Build Storybook Assets
      #   env:
      #     NODE_OPTIONS: "--max_old_space_size=4096"
        # run: npm run build-storybook-ng
      - name: Add .nojekyll file to allow for node_modules to be included in bundle
        run: touch _site/_docs/.nojekyll
      - name: List build dir contents
        run: ls -a _site
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: _site
