name: Build and Deploy Prototype
on:
  push:
    branches:
      - master
jobs:
  Build-HTML:
    uses: ./.github/workflows/build.yml
  Deploy-HTML:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: Build-HTML
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download HTML Assets
        uses: actions/download-artifact@v4
        with:
          name: html-assets
          path: ./docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs
          clean-exclude: pr-preview/
          force: false
