name: Deploy PRs
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  Get-Base-Href:
    runs-on: ubuntu-latest
    steps:
      - run: echo "base=/sam-design-system-site/pr-preview/pr-${{github.event.number}}/ >> $GITHUB_ENV"
  Build-HTML:
    needs: Get-Base-Href
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build.yml
    with:
        base: ${{env.base}}
  Deploy-HTML:
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    needs: Build-HTML
    steps:
        # Only needed because rossjrw/pr-preview-action needs to run in a git repo
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download HTML Assets
        # If closing PR, build will not occur so nothing to download
        if: github.event.action != 'closed'
        uses: actions/download-artifact@v4
        with:
          name: html-assets
          path: ./docs
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
